name: data
on:
  schedule:
    - cron: 0 0/4 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./olah.js
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: http://cerpenmu.com/100-cerpen-kiriman-terbaru
          downloaded_filename: cerpen.html
          postprocess: ./olah.js
